#!/usr/bin/with-contenv bash

# If we are debugging, enable trace
if [ "${DEBUG,,}" = "true" ]; then
  set -x
fi

rar2fs --seek-length=1 -o allow_other /data /data-unrar

echo "Rar2fs setup complete - Mounted data drive"
